export const SHOW_TODO_MODAL = "SHOW_TODO_MODAL";
export const HIDE_TODO_MODAL = "HIDE_TODO_MODAL";

export const TODO_ADD = "TODO_ADD";
export const TODO_DELETE = "TODO_DELETE";
export const TODO_EDIT = "TODO_EDIT";
export const TODO_CHANGE_STATUS = "TODO_CHANGE_STATUS";
export const TODO_CHANGE_SEARCH = "TODO_CHANGE_SEARCH";

